### ISSUE TITLE
User's Guide suggestion

### ISSUE THREAD

**Issue by dshaw619** [MrYsLab/pymata4#13]
Would be helpful to have instructions on how to update pymata4 somewhere in the User's Guide, perhaps on the Installing pymata4 page.  I saw (and successfully used) the instructions that were in Issue #10, but would probably be best to have them in a more obvious place.

**Comment by MrYsLab** [comment]
Good suggestion. You can find the addition [here.](https://mryslab.github.io/pymata4/upgrade/)
