### ISSUE TITLE
Feature request: SPI communications

### ISSUE THREAD

**Issue by Celldom-Han** [MrYsLab/pymata4#37]
I'm using an Arduino MKR WIFI 1010, with the Arduino MKR Therm Shield.

The shield takes a K type thermocouple, conditions the signal with a MAX31855 IC, and then uses SPI to communicate temperature information between the IC and the MKR board.

Problem: the pymata4 library doesn't seem to have SPI support, only I2C. (Please correct me if I'm wrong.)

Therefore, I cannot use pymata4 to control this sensor and similar devices. I'm wondering if it's possible to add SPI support into the library, or if there's some technical details that make it very difficult/impossible?

**Comment by MrYsLab** [comment]
I replied to your email with more detail. Essentially, I will not implement SPI support here, but I may provide it in my Telemetrix project. The sketch that supports pymata4 (FirmataExpress) is pretty much out of space for adding new features.
